@startuml "class diagram rsa"

class ConfigurationRsaGuided{
    bitLength: number
}



interface rsaKeys {
publicKey: publicKey
privateKey: privateKey
}

interface publicKey{
n: number
e: number
}

interface privateKey{
n: number
d: number
}

publicKey -|> rsaKeys
privateKey -|> rsaKeys
@enduml
